config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :installs
resources :pins
root 'pins#index'
end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
	before_action :find_pin, only: [:show, :edit, :update, :destroy]

	def index
		@pins = Pin.all.order('created_at DESC')
	end

	def new
		@pin = current_user.pins.build
	end

	def create
		@pin = current_user.pins.build(pin_params)
		if @pin.save
			redirect_to @pin, notice: "Successfully created new pin"
		else
			render 'new'
		end
	end
	def edit
		
	end

	def update
		if @pin.update(pin_params)
			redirect_to @pin, notice: 'pin was Successfully updated'
		else
			render 'edit'
		end
	end
	def destroy
		@pin.destroy
		redirect_to root_path
	end
	def show
		
	end

	private

	def pin_params
		params.require(:pin).permit(:title, :description, :image)
	end

	def find_pin
		@pin = Pin.find(params[:id])	
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
	%title Pin Board
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags
%body
	%nav.navbar.navbar-default
		.container
			.navbar-brand= link_to 'Pin Board', root_path

			- if user_signed_in?
				%ul.nav.navbar-nav.navbar-right
					%li= link_to 'New Pin', new_pin_path
					%li= link_to 'Account', edit_user_registration_path
					%li= link_to 'Sign out', destroy_user_session_path, method: :delete
			- else
				%ul.nav.navbar-nav.navbar-right
					%li= link_to 'Sign up', new_user_registration_path
					%li= link_to 'Sign in', new_user_session_path
	.container
		- flash.each do |name, msg|
			=content_tag :div, msg, class: "alert alert-info"
		=yield

app/views/pins/_form.html.haml
= simple_form_for @pin, html: { multipart: true } do |f|
	- if @pin.errors.any?
		#errors
			%h2
			=pluralize(@pins.errors.count, 'count')
			prevented this from saving
			%ul
				- @pins.errors.full_messages.each do |msg|
					%li= msg

	.form-group
		= f.input :image, input_html: { class: 'form_control'}

	.form-group
		= f.input :title, input_html: { class: 'form_control'}

	.form-group
		= f.input :description, input_html: { class: 'form_control'}
  
	= f.button :submit, class: 'btn btn primary'

app/views/pins/edit.html.haml
.col-md-6.col-md-offset-3
	%h2 Edit Pin
	= image_tag @pin.image.url(:medium)
	= render 'form'
	= link_to 'cancel', pin_path

app/views/pins/index.html.haml
#pins.transition-enabled
	- @pins.each do |pin|
		.box.panel.panel-default
			= link_to (image_tag pin.image.url(:medium)), pin
			.panel-body
				%p= link_to pin.title, pin

app/views/pins/new.html.haml
.col-md-6.col-md-offset-3
	%h2 New form

	= render 'form'
	= link_to "back", root_path

app/views/pins/show.html.haml
= image_tag @pin.image.url(:medium)
%h3= @pin.title
%p= @pin.description
Created by
%p= @pin.user.email

= link_to "back", root_path
= link_to 'edit', edit_pin_path
= link_to 'delete', pin_path, method: :delete, data: {confirm: 'Are you sure you want to delete this pin?'}